### ISSUE TITLE
Incorrect pseudocode for ComputeBigBoxRatio?

### ISSUE THREAD

**Issue by gjtorikian** [CBrauer/CypressPoint.github.io#1]
Stumbled upon your ML and finance experiments by pure chance. Good stuff! I have a question about your code in [5.1 The BoxRatio predictor](http://blog.cypresspoint.com/2018/08/06/Article.html).

It seems that some values are not introduced anywhere else, and I'm having trouble following the logic of where they came from. For example:

* Lines 19 and 20 refer to `averageVolume`, but this is not defined earlier
* Lines 11/12 and 16/17 refer to `ave1` and `ave2`, but these are never used
* Line 26 introduce `high[k]` and `low[k]` without showing a definition as to where they are from, either

**Comment by gjtorikian** [comment]
cc @CBrauer (just noticed you're not watching the repo -- it's a quirky setting that needs to be configured manually in the Settings page)

**Comment by CBrauer** [comment]
Hi Garen,

Wow! Somebody actually read my Pseudo code! Good ketch Garen.  Lines 19 and 20 should be **averageTotalVolume**, which is defined above.  The **high** and **low** values are the high/low values so far in the trading day.  I will change the web site.  I appreciate you pointing this out.

The **BoxRatio** algorithm is taken from the work of Mr. Richard W. Arms, Jr. on Equivolume.  For more information you can Google his work.
Charles

**Comment by gjtorikian** [comment]
Hah! No worries. I really enjoyed the technical analysis. 

If it's of any interest, I'm in the process of turning the pseudocode into runnable Python code, just to have more fun testing the TPOT logic. When that's done I can share that with you here if you'd like?

**Comment by CBrauer** [comment]
Hi Garen.  

Thanks for your comments.  I’m looking forward hearing what you think about TPOT.  I think those guys do great work.

HedgeTools uses a real-time feed from IQFeed.net, and I can ask for 10-seconds summaries. 

I’m curious about how your get your data.  

Charles

**Comment by gjtorikian** [comment]
Ah, I haven't actually built anything working with incoming live data. Right now I just want to back test with historical data to validate the ideas.
